name: Build, run unit tests and check code coverage
permissions: read-all

on:
  push:
    branches: [ "main", "epic/*" ]
  pull_request:
    branches: [ "main", "epic/*" ]

jobs:

  build_and_test_eulersidentity:
    uses: ./.github/workflows/BuildAndTest.yml
    with:
      FOLDER_UNDER_TEST: "EulersIdentity"
      MODULE_UNDER_TEST: "Sde.EulersIdentity"
      TEST_FOLDER: "EulersIdentity.Test"
      TEST_PROJECT: "EulersIdentity.Test.csproj"
